# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup project dependencies 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: get code dependencies
      run: dotnet restore hello_mct.csproj

    - name: Build code
      run: dotnet build hello_mct.csproj --no-restore

    - name: Unit test code
      run: dotnet test hello_mct.csproj --no-build --verbosity normal
